{
 "title": "Furnace",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "State",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": {
    "0": { "refId": "A" },
    "ZabbixServer": {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "AVG temperature",
   "type": "singlestat",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": {
      "filter": "Average sensor #1 and 2# temperature"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Kitchen AIR",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Furnace sensor air temperature" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Water circuit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": {
      "filter": "Furnace sensor water circuit temperature"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Water circuit",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": {
      "filter": "Furnace sensor water circuit temperature"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sensors AVG temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": {
      "filter": "Average sensor #1 and 2# temperature"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Kitchen AIR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Furnace sensor air temperature" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SENSOR #1 (AIR, Humidity)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Room sensor #1 temperature" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Room sensor #1 humidity" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SENSOR #2 (AIR, Humidity)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Room sensor #2 temperature" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Room sensor #2 humidity" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Water Used Total (Litres)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Water" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Water meter" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Water meter (L/Min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "litre" }
   ],
   "targets": [
    {
     "application": { "filter": "Water" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "count",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "count(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Water meter" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outside weather (AIR, Humidity)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Outside weather temperature" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Outside weather humidity" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outside weather (Pressure & Wind Speed)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Outside weather pressure" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Furnace" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Microserver" },
     "item": { "filter": "Outside weather wind speed" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}